# Site settings
title: Personal portfolio page
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sam Kwon
user_description: 
user_title: Software Developer
email: samuski30@gmail.com
twitter_username: 
github_username:  samuski
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
